"""
report_generator.py — PDF Report Generation using ReportLab

Generates a clean, professional plagiarism analysis report
that can be downloaded by the user.
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, HRFlowable, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
import os


# ─────────────────────────────────────────────
# Color Palette
# ─────────────────────────────────────────────

DARK_BG     = colors.HexColor("#0f0f1a")
ACCENT      = colors.HexColor("#6c63ff")
ACCENT_SOFT = colors.HexColor("#a59dff")
TEXT_LIGHT  = colors.HexColor("#e8e6ff")
TEXT_MUTED  = colors.HexColor("#9490b5")
RED_RISK    = colors.HexColor("#ff4f6d")
AMBER_RISK  = colors.HexColor("#ffb347")
GREEN_SAFE  = colors.HexColor("#4caf7d")
LIGHT_GRAY  = colors.HexColor("#f0eff8")
MID_GRAY    = colors.HexColor("#d0cde8")
SECTION_BG  = colors.HexColor("#f7f6ff")


def _risk_color(risk_level: str):
    mapping = {
        "Low Risk": GREEN_SAFE,
        "Moderate Risk": AMBER_RISK,
        "High Risk": RED_RISK,
        "Critical": RED_RISK,
    }
    return mapping.get(risk_level, ACCENT)


def generate_report(analysis_result: dict, filename: str, output_dir: str) -> str:
    """
    Generate a professional PDF report from analysis results.

    Args:
        analysis_result: Dict returned by analyzer.analyze()
        filename: Original uploaded filename
        output_dir: Directory to save the PDF

    Returns:
        Full path to the generated PDF.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    pdf_filename = f"PlagiarismReport_{timestamp}.pdf"
    pdf_path = os.path.join(output_dir, pdf_filename)

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title="Plagiarism Analysis Report"
    )

    styles = getSampleStyleSheet()
    story = []

    # ── Header ──────────────────────────────────
    story.append(Spacer(1, 0.3 * cm))

    title_style = ParagraphStyle(
        "CustomTitle",
        fontName="Helvetica-Bold",
        fontSize=22,
        textColor=ACCENT,
        alignment=TA_CENTER,
        spaceAfter=4
    )
    story.append(Paragraph("PLAGIARISM ANALYSIS REPORT", title_style))

    subtitle_style = ParagraphStyle(
        "Subtitle",
        fontName="Helvetica",
        fontSize=10,
        textColor=TEXT_MUTED,
        alignment=TA_CENTER,
        spaceAfter=2
    )
    story.append(Paragraph("Generated by PlagiaGuard™ Academic Integrity Tool", subtitle_style))
    story.append(Spacer(1, 0.3 * cm))
    story.append(HRFlowable(width="100%", thickness=1.5, color=ACCENT, spaceAfter=10))
    story.append(Spacer(1, 0.3 * cm))

    # ── Meta Table ──────────────────────────────
    meta_data = [
        ["Document Analyzed:", filename],
        ["Analysis Date:", datetime.now().strftime("%B %d, %Y at %H:%M")],
        ["Sentences Analyzed:", str(analysis_result.get("total_sentences_analyzed", "—"))],
        ["Flagged Sentences:", str(analysis_result.get("flagged_sentence_count", 0))],
    ]
    meta_table = Table(meta_data, colWidths=[5 * cm, 12 * cm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), ACCENT),
        ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#333333")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [SECTION_BG, colors.white]),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (0, -1), 8),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 0.5 * cm))

    # ── Score Summary Card ───────────────────────
    score = analysis_result.get("plagiarism_percentage", 0)
    original = analysis_result.get("original_percentage", 100)
    risk = analysis_result.get("risk_level", "Low Risk")
    risk_col = _risk_color(risk)

    section_header_style = ParagraphStyle(
        "SectionHeader",
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=ACCENT,
        spaceBefore=10,
        spaceAfter=6
    )
    story.append(Paragraph("OVERALL SIMILARITY SCORE", section_header_style))

    score_data = [
        [
            Paragraph(f"<font color='#{_hex(risk_col)}'><b>{score}%</b></font>\nPlagiarism Detected", 
                     ParagraphStyle("sc", fontName="Helvetica-Bold", fontSize=18, alignment=TA_CENTER, leading=22)),
            Paragraph(f"<font color='#{_hex(GREEN_SAFE)}'><b>{original}%</b></font>\nOriginal Content",
                     ParagraphStyle("sc2", fontName="Helvetica-Bold", fontSize=18, alignment=TA_CENTER, leading=22)),
            Paragraph(f"<font color='#{_hex(risk_col)}'><b>{risk}</b></font>\nRisk Level",
                     ParagraphStyle("sc3", fontName="Helvetica-Bold", fontSize=18, alignment=TA_CENTER, leading=22)),
        ]
    ]
    score_table = Table(score_data, colWidths=[5.7 * cm, 5.7 * cm, 5.7 * cm])
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), SECTION_BG),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWHEIGHTS", (0, 0), (-1, -1), 1.8 * cm),
        ("BOX", (0, 0), (-1, -1), 1, MID_GRAY),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, MID_GRAY),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 0.5 * cm))

    # ── Per-Reference Breakdown ─────────────────
    breakdown = analysis_result.get("per_reference_breakdown", [])
    if breakdown:
        story.append(Paragraph("REFERENCE COMPARISON BREAKDOWN", section_header_style))
        breakdown_data = [["Reference #", "TF-IDF Score", "Jaccard Score", "Blended Score", "Flagged Sentences"]]
        for ref in breakdown:
            breakdown_data.append([
                f"Reference {ref['reference_index'] + 1}",
                f"{ref['cosine_similarity']}%",
                f"{ref['jaccard_similarity']}%",
                f"{ref['blended_score']}%",
                str(ref['flagged_sentence_count'])
            ])

        bd_table = Table(breakdown_data, colWidths=[3 * cm, 3.2 * cm, 3.2 * cm, 3.2 * cm, 4.2 * cm])
        bd_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SECTION_BG]),
            ("GRID", (0, 0), (-1, -1), 0.5, MID_GRAY),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(bd_table)
        story.append(Spacer(1, 0.5 * cm))

    # ── Flagged Sentences ───────────────────────
    flagged = analysis_result.get("flagged_sentences", [])
    if flagged:
        story.append(Paragraph("FLAGGED PASSAGES", section_header_style))

        flag_note_style = ParagraphStyle(
            "FlagNote", fontName="Helvetica", fontSize=8.5,
            textColor=TEXT_MUTED, spaceAfter=6
        )
        story.append(Paragraph(
            "The following sentences from the submitted document closely match content in one or more reference sources.",
            flag_note_style
        ))

        sent_label_style = ParagraphStyle(
            "SentLabel", fontName="Helvetica-Bold", fontSize=8,
            textColor=ACCENT, spaceBefore=6
        )
        sent_text_style = ParagraphStyle(
            "SentText", fontName="Helvetica", fontSize=8.5,
            textColor=colors.HexColor("#222222"), leading=13, spaceAfter=2
        )
        match_style = ParagraphStyle(
            "MatchStyle", fontName="Helvetica-Oblique", fontSize=8,
            textColor=TEXT_MUTED, leading=12, spaceAfter=4
        )

        for idx, item in enumerate(flagged[:20], 1):  # Limit to 20 in report
            block = [
                Paragraph(f"Flagged Passage #{idx}  —  {item['similarity']}% match", sent_label_style),
                Paragraph(f"Source: {item['sentence']}", sent_text_style),
                Paragraph(f"Matched with: {item['matched_with'][:200]}...", match_style),
                HRFlowable(width="100%", thickness=0.5, color=MID_GRAY, spaceAfter=2),
            ]
            story.append(KeepTogether(block))

    # ── Footer ──────────────────────────────────
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=MID_GRAY))
    footer_style = ParagraphStyle(
        "Footer", fontName="Helvetica", fontSize=7.5,
        textColor=TEXT_MUTED, alignment=TA_CENTER, spaceBefore=6
    )
    story.append(Paragraph(
        "PlagiaGuard™ Academic Integrity Tool  •  Report generated for educational purposes  •  "
        f"{datetime.now().strftime('%Y')}",
        footer_style
    ))

    doc.build(story)
    return pdf_path


def _hex(color) -> str:
    """Convert ReportLab color to hex string (without #)."""
    r = int(color.red * 255)
    g = int(color.green * 255)
    b = int(color.blue * 255)
    return f"{r:02x}{g:02x}{b:02x}"
